### ISSUE TITLE
Add `CLSCompliantAttribute`

### ISSUE THREAD

**Issue by saucecontrol** [bgrainger/IndexRange#10]
Like strong naming, this is generally pointless these days, but it's viral.  If you have a project that declares CLS compliance, you get compiler warnings on any types exposed in public APIs that are not also declared CLS compliant.

All the BCL assemblies are marked CLS compliant, so that's a difference between this package and what would be the 'official' one if it existed.

```C#
[assembly: CLSCompliant(true)]
```

**Comment by bgrainger** [comment]
Available in [v1.0.2](https://github.com/bgrainger/IndexRange/releases/tag/v1.0.2).

**Comment by saucecontrol** [comment]
Wow, that was speedy, thanks!
