### ISSUE TITLE
Support UWP (min version < 16299)

### ISSUE THREAD

**Issue by Baka632** [bgrainger/IndexRange#12]
Though we can use IndexRange in UWP that minimum version is 16299 or later, former version of UWP can't use this library because they can't use .NET Standard 2.0. 

For developers who still want to create apps on former version of Windows (like Windows 10 Mobile), it would be useful to support ```uap10.0```.

The main issue was the lack of support for targeting ```uap10.0```, so I used [MSBuildSdkExtras](https://github.com/novotnyllc/MSBuildSdkExtras) which allows us to target ```uap10.0```.

I've completed a draft version in [here](https://github.com/Baka632/IndexRange.Uwp).

**Comment by Baka632** [comment]
Sorry, I forget to add NuGet package reference for ```MSBuild.Sdk.Extras```

Missing this package will lead to a build failure

**Comment by Baka632** [comment]
I think that ```MSBuild.Sdk.Extras``` supports Linux.

**Comment by bgrainger** [comment]
I published a beta version with UAP support (based on your draft): https://www.nuget.org/packages/IndexRange/1.0.3-beta.1

Let me know if that works for you, and I'll publish a release package.

**Comment by Baka632** [comment]
It works fine with string, thanks!
![image](https://github.com/bgrainger/IndexRange/assets/48171809/d24be776-f222-409b-87d6-810b25c9178e)

But I can't use Range with arrays (Index works fine)
If I define GetSubArray<T> in my own ```RuntimeHelper.cs```, compiler will complain that ```RunClassConstructor``` is missing (in ```XamlTypeInfo.g.cs```)

![image](https://github.com/bgrainger/IndexRange/assets/48171809/29d1cd86-31c9-434f-ad34-78199a9bcf16)

Any solutions?

**Comment by Baka632** [comment]
If I use ```Span<T>```, I will receive an "internal compiler error" when I use ```Release``` configuration.
(Works fine with ```Debug``` configuration)

**Comment by Baka632** [comment]
This is my sample project: [Baka632/IndexRangeTest.Uwp](https://github.com/Baka632/IndexRangeTest.Uwp)

**Comment by bgrainger** [comment]
Shipped in [v1.0.3](https://github.com/bgrainger/IndexRange/releases/tag/v1.0.3).
