### ISSUE TITLE
Source-only package

### ISSUE THREAD

**Issue by drewnoakes** [bgrainger/IndexRange#13]
This would make a good source-only package, so consumers don't need to ship extra DLLs.

https://andrewlock.net/creating-source-only-nuget-packages/

**Comment by bgrainger** [comment]
Agreed. In the meantime, PolySharp might be a good alternative: https://github.com/Sergio0694/PolySharp.

**Comment by bgrainger** [comment]
Per https://github.com/dotnet/runtime/issues/28285#issuecomment-1773870880:

> PolySharp can also make its generated Index/Range public, but then each project's definition of them is distinct. For public APIs, I'd still recommend the IndexRange package, as those types can be shared between projects.

Based on that feedback, my recommendation would be:

1. If you're using the types internally (and/or want source-only support), use PolySharp.
2. If you're exposing the types in your public API (and/or need interop between different libraries), use IndexRange (or the new [Microsoft.Bcl.Memory package](https://www.nuget.org/packages/Microsoft.Bcl.Memory)); IndexRange will remain as a binary package to support this scenario.
