### ISSUE TITLE
Support .NET Framework 3.5

### ISSUE THREAD

**Issue by davidhunter22** [bgrainger/IndexRange#5]
It would be useful to support .NET Framework 3.5 as it is a Long Term Support version that does not go out of support for a few years.

I gave this a try and it was trivial to do. The main issue was the lack of support for ValueTuple so I added a conditional package reference to the package ValueTupleBridge which back ports ValueTuple support

**Comment by bgrainger** [comment]
How important is this? I'm curious how many people might be trying to use a recent C# compiler and trying to use C# 8.0 to target .NET 3.5.

As you pointed out, `ValueTuple` isn't supported on .NET 3.5, so an additional NuGet package (that only has 30K downloads) is required. (OTOH, that's more downloads than IndexRange itself, which may indicate that enabling new language features for old framework versions just isn't commonly needed.)

**Comment by davidhunter22** [comment]
I doubt there are tons of requirements for this. Although it's no really C# 8.0 related as I suspect older C# compiler could still be used.
I have a small software company and we have a client who is only now upgrading from 3.5!!! 
Having the 3.5 support makes their transistion easier a they can start using Index and Range immediatly. They want to build 3.5 for a while so they can run old and new frameworks side by side for testing till they kill the old.

**Comment by bgrainger** [comment]
Index and Range is a C# 8.0 feature; there's no need for this package before C# 8.

**Comment by davidhunter22** [comment]
Ah OK guess I should have checked that.
Anyway the upshot is I can't alk for anyone else but I definitly have a use case for .NET 3.5

**Comment by davidhunter22** [comment]
BTW Also thanks for doing this package

**Comment by bgrainger** [comment]
Thanks to @ash-hat (https://github.com/bgrainger/IndexRange/pull/6#issuecomment-900910032) I've been able to produce a package that supports .NET 3.5.

It's currently available as a pre-release: https://www.nuget.org/packages/IndexRange/1.0.1-beta.1

If you need .NET 3.5 support, please test it out and let me know if it's working!

**Comment by bgrainger** [comment]
Fixed in [v1.0.1](https://github.com/bgrainger/IndexRange/releases/tag/v1.0.1).
