### ISSUE TITLE
Upgrade nuget package references

### ISSUE THREAD

**Issue by davidhunter22** [bgrainger/IndexRange#7]
Upgrade the packages referenced to the latest compatible versions.
Note xunit.runner.visualstudio can't move to the latest version as it no longer supports older frameworks versions

**Comment by bgrainger** [comment]
Fixed in https://github.com/bgrainger/IndexRange/commit/6292d638ddf4f0c5567b7c43b967485f48b3c836 and https://github.com/bgrainger/IndexRange/commit/0bbaae6b8f4c1d1a25031aee6e4dc464e88bddd9.
